### ISSUE TITLE
forestplot([[0.2,0.7]]) works, but forestplot([[0.2,0.6]]) does not.

### ISSUE THREAD

**Issue by Jan-van-Waaij** [PharmCat/ForestPlot.jl#2]
Hallo!

I am using your package to compare credible sets for different situations. If the interval is small, I get "ArgumentError: range step cannot be zero". So for example forestplot([[0.2,0.6]]) gives an error, but forestplot([[0.2,0.7]]) does not. 

How can I solve this problem?

Best,

Jan

**Comment by Jan-van-Waaij** [comment]
I could solve the issue by replacing line 89 "ticks = collect(minx:0.2*floor((maxx - minx)/0.2/4):maxx)" by "collect(range(minx, maxx, length=5))". 0.2*floor((maxx - minx)/0.2/4) is sometimes zero when maxx is close to minx.

**Comment by PharmCat** [comment]
> I could solve the issue by replacing line 89 "ticks = collect(minx:0.2_floor((maxx - minx)/0.2/4):maxx)" by "collect(range(minx, maxx, length=5))". 0.2_floor((maxx - minx)/0.2/4) is sometimes zero when maxx is close to minx.

Thank you very much! It work great! :)
